export const CUISINES = [
  "Japanese",
  "Chinese",
  "Korean",
  "Thai",
  "Vietnamese",
  "Indian",
  "Mexican",
  "Italian",
  "French",
  "Spanish / Tapas",
  "Greek",
  "Turkish",
  "Lebanese / Middle Eastern",
  "Moroccan",
  "Ethiopian",
  "Peruvian",
  "Brazilian",
  "American BBQ",
  "German",
  "Malaysian",
] as const;

export const LANGUAGES = [
  { code: "en", name: "English" },
  { code: "zh", name: "Chinese (Simplified)" },
  { code: "zh-TW", name: "Chinese (Traditional)" },
  { code: "ja", name: "Japanese" },
  { code: "ko", name: "Korean" },
  { code: "es", name: "Spanish" },
  { code: "fr", name: "French" },
  { code: "de", name: "German" },
  { code: "pt", name: "Portuguese" },
  { code: "it", name: "Italian" },
  { code: "ru", name: "Russian" },
  { code: "ar", name: "Arabic" },
  { code: "hi", name: "Hindi" },
  { code: "th", name: "Thai" },
  { code: "vi", name: "Vietnamese" },
  { code: "ms", name: "Malay" },
  { code: "id", name: "Indonesian" },
  { code: "tr", name: "Turkish" },
  { code: "nl", name: "Dutch" },
  { code: "sv", name: "Swedish" },
] as const;
